server:
  port: 8003
spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8002/eureka/
    register-with-eureka: true
    fetch-registry: true
